### ISSUE TITLE
404 when no data or wrong url

### ISSUE THREAD

**Issue by SamuelRott** [Internet4000/radio4000-api#10]
If I fetch  `endpoint/v1/channels/channelWithoutTracks/tracks` or `endpoint/v1/channels/wrongId/tracks` I get a 404 with a nice error msg, "Data does not exist".
Is it wanted, same response for two different scenario ?
What about returning an empty array when fetching "CHANNELWIHTOUTTRACKS/tracks" ?

**Comment by hellerve** [comment]
I think the second URL should behave like that, and it would be prudent if the first URL behaved like you suggested, i.e. return an empty array.
