### ISSUE TITLE
gt filterMethod always send empty array

### ISSUE THREAD

**Issue by SamuelRott** [internet4000/radio4000-api#12]
Hello,

The gt filterMethod seems broken.

For example I should fetch all channels with this url but i get an empty array.
`https://api.radio4000.com/v1/channels?created.gt=1`

I tried with `updated` queryParam, also empty array.

**Comment by SamuelRott** [comment]
this line
`gt: (channel, val) => channel.length > val`
 in
`radio4000-api/v1/firebase/adapter.js`

You are checking the length of what is suppose to an integer.

**Comment by hellerve** [comment]
I think the idea was getting the length of the tracks, probably. I might be culpable.

**Comment by hugurp** [comment]
closed by #20
