### ISSUE TITLE
Tracks get lost ?

### ISSUE THREAD

**Issue by SamuelRott** [internet4000/radio4000-api#16]
the length of 
 `https://api.radio4000.com/v1/channels.[0].tracks`
radio Oskar : 1164
 diverge form 
`https://api.radio4000.com/v1/channels/idOfFirstRadio/tracks`.
radio Oskar : 1168

It should be two ways to access the same information.
What is the difference between those two URL ?

**Comment by oskarrough** [comment]
The first uses `apiGetChannelsFiltered` whereas the second one uses `apiGetChannelTrack`. But not sure why. Using the REST api shows the same:

1168 tracks:  
https://radio4000.firebaseio.com/tracks.json?orderBy=%22channel%22&equalTo=%22-JXHtCxC9Ew-Ilck6iZ8%22

1164 tracks:  
https://radio4000.firebaseio.com/channels/-JXHtCxC9Ew-Ilck6iZ8.json

**Comment by hugurp** [comment]
closed by #20
