### ISSUE TITLE
Using Firebase directly

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-api#17]
Let's consider advocating to use Firebase directly instead of abstracting it all away. Ala https://github.com/HackerNews/API. Mainly because I'm not sure the abstractions are worth it and that I don't feel like maintaining queries etc., when it already works, if you use Firebase directly.

It comes with some tradeoffs. We will use radio4000.firebaseio.com and not api.radio4000.com. We can't modify anything. But it is simpler to reason about. If we one day decide to ditch Firebase, we should of course make our own API. But until that day, I believe we're better served with Firebase directly. First and foremost with their REST API (not the SDK).

**Comment by hugurp** [comment]
Then let's list what we have to to make it happen

- [ ] firebase security rules need to be 100% sure
- [ ] maybe we fix the image issue before, removing it from relationships and making it a string key in the channel model
-  [ ] we gotta update all application depending on the then deprecated `api.`
- [ ] write new documentation

**Comment by hugurp** [comment]
closed by #20
