### ISSUE TITLE
fix html URL at /oembed

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-api#24]
Go to https://api.radio4000.com/oembed?slug=918

```
html: "<iframe width="320" height="400" src="http://us-central1-radio4000-embed-api-4ac07.cloudfunctions.net/iframe?slug=918" frameborder="0"></iframe>",
```

The `src` should be `api.radio4000.com/iframe?slug=918`

**Comment by oskarrough** [comment]
Seems we can't rely on `request.headers.host` https://github.com/internet4000/radio4000-api/blob/master/src/app.js#L76
