### ISSUE TITLE
Update license to aGPLv3

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-api#34]
Because this is run on a server, when radio4000-cms is run on client.

https://www.gnu.org/licenses/agpl-3.0.html

Note that all our code that runs on server should use this license (instead of GPLv3).

**Comment by oskarrough** [comment]
Cool. So if I understand it correctly the difference is that anyone who modifies the code is required to release the source code somehow (and not hide it behind a server)?

**Comment by hugurp** [comment]
yes! I read why it is different from GPLv3, but nut sure why.

**Comment by hugurp** [comment]
done
