### ISSUE TITLE
Iframe 100% width

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-api#35]
how can we do to have a responsive iframe?
`width: 100%` does not work

**Comment by oskarrough** [comment]
jsbin please

**Comment by oskarrough** [comment]
http://jsbin.com/qibopux/edit?html,css,output

**Comment by hugurp** [comment]
https://jsbin.com/qibopux/edit?html,css,output

**Comment by oskarrough** [comment]
I don't understand. Or is it a cross-browser issue? With `width="100%"` it's responsive here (chrome/ff/mac).

**Comment by hugurp** [comment]
Yo sorry, sent the wrong link.
```
iframe {
 width: 100%;
}
```
That won't work, so it has to always be inline.
